// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCylJnQ8HdOqviv_GC6WH7sWojzR68odo',
    appId: '1:456336555388:web:14be0801c4e743ead2b8f9',
    messagingSenderId: '456336555388',
    projectId: 'date-app-2ebc0',
    authDomain: 'date-app-2ebc0.firebaseapp.com',
    storageBucket: 'date-app-2ebc0.appspot.com',
    measurementId: 'G-3Z1MPGSVN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRTHcKAFE2vwBXjR2tpZlaS2-rcx_99sI',
    appId: '1:456336555388:android:51c8fcb72eb32a3dd2b8f9',
    messagingSenderId: '456336555388',
    projectId: 'date-app-2ebc0',
    storageBucket: 'date-app-2ebc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCELHTa4W97WGkVdY0Ud2Q86Uq4y_89zA4',
    appId: '1:456336555388:ios:1abd216d68dde513d2b8f9',
    messagingSenderId: '456336555388',
    projectId: 'date-app-2ebc0',
    storageBucket: 'date-app-2ebc0.appspot.com',
    iosBundleId: 'com.example.myapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCELHTa4W97WGkVdY0Ud2Q86Uq4y_89zA4',
    appId: '1:456336555388:ios:1abd216d68dde513d2b8f9',
    messagingSenderId: '456336555388',
    projectId: 'date-app-2ebc0',
    storageBucket: 'date-app-2ebc0.appspot.com',
    iosBundleId: 'com.example.myapp1',
  );
}
